name: Terraform Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
